### ISSUE TITLE
Change description in settings

### ISSUE THREAD

**Issue by kirkins** [cvatch/cvatch.github.io#15]
Change description in settings and also make sure you have a link to your website in that description.

This improves the workflow because you can make a change, or see changes, then quickly click through to view the live site.

**Comment by cvatch** [comment]
Where is this description that you speak of in the settings? the settings of the repo?

**Comment by kirkins** [comment]
![screenshot from 2017-06-29 18-19-25](https://user-images.githubusercontent.com/9503662/27713000-86c3023a-5cf7-11e7-9829-0f80ac883e23.png)

There should be an edit button on it actually.
