### ISSUE TITLE
Remove Find out more button

### ISSUE THREAD

**Issue by cvatch** [cvatch/cvatch.github.io#22]
I would like to remove the first find out more button n the header

**Comment by cvatch** [comment]
how do you comment something out
i want to take out the header all together cause that is where the find out more button and the text is i want to remove
but i might want it back after so i dont wanna just delete

**Comment by kirkins** [comment]
Should be able to do that by deleting this:

https://github.com/cvatch/cvatch.github.io/blob/master/_includes/header.html#L6

Or comment with this

    


Read more: http://html.com/tags/comment-tag/#ixzz4lQITFSck
