### ISSUE TITLE
Change Main image under Infinite Actitivies 

### ISSUE THREAD

**Issue by cvatch** [cvatch/cvatch.github.io#5]
Would like to update the main image that you first see of the skyline.

**Comment by kirkins** [comment]
I think that image is this one here

https://github.com/cvatch/cvatch.github.io/blob/master/img/bg.jpg

Try this:

1. Cut image to similar size in photoshop_(optional?)_
2. Name it bg.jpg on your PC
3. Goto https://github.com/cvatch/cvatch.github.io/tree/master/img
4. Hit upload file button, and drag/drop
5. Make a pull request

**Comment by kirkins** [comment]
Oh yeah on your pull request make sure to reference this issue. You can do that with a hash and the issue ID from the url. 

So #5 that way the pull will be tied to this thread, and everyone involved here will be notified. _(Good habit)_

**Comment by kirkins** [comment]
Like the image but it's hard to read the text now. Maybe shift the color or something in photoshop?

**Comment by cvatch** [comment]
this is why i am trying to change the text to white

**Comment by kirkins** [comment]
Going to keep this one open because it still needs a better solution.

**Comment by cvatch** [comment]
going to close this one because i like the image and we have another issue open for the font and css stuff
