### ISSUE TITLE
Update Site Settings File

### ISSUE THREAD

**Issue by kirkins** [cvatch/cvatch.github.io#7]
@cvatch I accidentally merged changes from master into pages that I shouldn't have [here](https://github.com/cvatch/cvatch.github.io/pull/3/files).

Take a look at this file and make the edits needed 👍

https://github.com/cvatch/cvatch.github.io/blob/master/_config.yml

**Comment by kirkins** [comment]
Related commit https://github.com/cvatch/cvatch.github.io/commit/ac18554f843a69608111378153fd6378df514b86

**Comment by cvatch** [comment]
page build failure due to error on facebook username - fixed under commit 564fdac
